// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfjldryrvjyllhxnurvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmamxkcnlydmp5bGxoeG51cnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTkzNTUsImV4cCI6MjA3NDI5NTM1NX0._8ump1rdet4RqRcGO6nJtur5kP939wcli7ZwFwzczOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});